### ISSUE TITLE
Installer gets confused by aarch64-linux

### ISSUE THREAD

**Issue by ajeetdsouza** [jpillora/installer#17]
Hey @jpillora, I was trying to use `installer` with [zoxide](https://github.com/ajeetdsouza/zoxide), but it seems to be downloading the aarch64 binary instead of amd64 on Linux.

Here's the case statement generated by `curl 'https://i.jpillora.com/ajeetdsouza/zoxide!'`:

```shell
case "${OS}_${ARCH}" in
"linux_amd64")
	URL="https://github.com/ajeetdsouza/zoxide/releases/download/v0.7.0/zoxide-aarch64-unknown-linux-musl.tar.gz"
	FTYPE=".tar.gz"
	;;
"linux_arm")
	URL="https://github.com/ajeetdsouza/zoxide/releases/download/v0.7.0/zoxide-armv7-unknown-linux-musleabihf.tar.gz"
	FTYPE=".tar.gz"
	;;
"darwin_amd64")
	URL="https://github.com/ajeetdsouza/zoxide/releases/download/v0.7.0/zoxide-x86_64-apple-darwin.tar.gz"
	FTYPE=".tar.gz"
	;;
*) fail "No asset for platform ${OS}-${ARCH}";;
esac
```

**Comment by jpillora** [comment]
Yep needs better arm support!

**Comment by jpambrun** [comment]
Same problem with delta, fd, lsd. I imagine the aarch64 tag is common among rust projects.

k9s gives me ppc.

Better arch heuristics is probably needed..
