### ISSUE TITLE
It looks like it doesn't work on Windows platforms

### ISSUE THREAD

**Issue by dylanbai8** [jpillora/installer#2]
![90](https://user-images.githubusercontent.com/26950227/40482850-b0453472-5f88-11e8-94fd-66a6e992742b.JPG)

It looks like it doesn't work on Windows platforms！

**Comment by jpillora** [comment]
Yes! Does windows have curl? Can windows pipe commands to other commands?
Does batch/cmd run scripts from stdin? Does Windows have stdin? Many
questions...

**Comment by dylanbai8** [comment]
That's a pity. However, this project is still very very great！
