### ISSUE TITLE
Ability only allow a specific repository

### ISSUE THREAD

**Issue by zifeo** [jpillora/installer#28]
Great work! When self-hosting, users will likely want to only support one repository for security reasons (e.g. not allowing third-party or bad-party to install binaries through their domains). Also, I believe the documentation and support for self-hosting should be improved (e.g. parameters, docker image, helm, etc.).

**Comment by jpillora** [comment]
Sounds good, would ‘FORCE_REPO=foobar’ work for you?

and can you raise a PR 😄?
