### ISSUE TITLE
Some versions are not parsing properly

### ISSUE THREAD

**Issue by electrocucaracha** [jpillora/installer#32]
There are some versions which are removed the hyphen char

```
$ curl -s 'https://i.jpillora.com/GoogleContainerTools/kpt@v1.0.0-beta.24!!'
echo 'release tag v1.0.0beta.24 not found'
$ curl -s https://api.github.com/repos/GoogleContainerTools/kpt/releases | grep '"tag_name": "v1.0.0-beta.24",'
    "tag_name": "v1.0.0-beta.24",
```

So apparently this [conditional](https://github.com/jpillora/installer/blob/v0.4.1/handler/handler_execute.go#L93) fails, maybe [splitHalf](https://github.com/jpillora/installer/blob/v0.4.1/handler/handler.go#L125) method is modifying the value

## Update 

It works without sudo move option.
```
curl -s 'https://i.jpillora.com/GoogleContainerTools/kpt@v1.0.0-beta.24!' | bash
```

**Comment by jpillora** [comment]
Thanks will check it out

Try dropping one off the !

?

**Comment by electrocucaracha** [comment]
I wasn't aware that functionality was dropped in `v0.3.3`. I'll close this, but it's weird why the release tag removes the hyphen character, I'm not sure if that can causes future issues.
