### ISSUE TITLE
Installer generates incorrect script for Linux and Darwin

### ISSUE THREAD

**Issue by mcsakoff** [jpillora/installer#8]
Running, e.g.:

```
curl -fsSL https://i.jpillora.com/jesseduffield/lazygit@v0.16.2 | bash
```

fails with `Error: No asset for platform linux-amd64` on Linux and `Error: No asset for platform darwin-amd64` on Mac.

The reason is lines ~45-47
```bash
     case `uname -s` in
     Darwin) OS="darwin";;
     Linux) OS="linux";;
```
and ~63-96:
```bash
    case "${OS}_${ARCH}" in
    "Linux_386") ...
    "Linux_amd64") ...
    "Linux_arm") ...
    "Darwin_386") ...
    "Darwin_amd64") ...
```
.

The cases must be lowercased as well.

**Comment by jpillora** [comment]
See https://i.jpillora.com/jesseduffield/lazygit@v0.16.2?type=script
